#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────
# deploy.sh – Deploy SLD BOM Extraction Azure infrastructure
# Usage:
#   ./infra/deploy.sh                    # dev (default)
#   ./infra/deploy.sh prod               # production
#   ./infra/deploy.sh dev westus2        # dev in specific region
# ──────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV="${1:-dev}"
LOCATION="${2:-koreacentral}"
RESOURCE_GROUP="rg-sldbom-${ENV}"
PARAM_FILE="${SCRIPT_DIR}/parameters/${ENV}.bicepparam"

# ── Validate ───────────────────────────────────────────────────────
if [[ ! -f "$PARAM_FILE" ]]; then
  echo "ERROR: Parameter file not found: $PARAM_FILE"
  echo "Available: $(ls "${SCRIPT_DIR}/parameters/")"
  exit 1
fi

if ! command -v az &>/dev/null; then
  echo "ERROR: Azure CLI (az) is not installed."
  echo "Install: https://learn.microsoft.com/cli/azure/install-azure-cli"
  exit 1
fi

# ── Check login ────────────────────────────────────────────────────
echo "── Checking Azure CLI login..."
if ! az account show &>/dev/null; then
  echo "Not logged in. Running 'az login'..."
  az login
fi

SUBSCRIPTION=$(az account show --query name -o tsv)
echo "   Subscription: ${SUBSCRIPTION}"
echo "   Environment:  ${ENV}"
echo "   Region:       ${LOCATION}"
echo "   Resource Group: ${RESOURCE_GROUP}"
echo ""

# ── Confirm ────────────────────────────────────────────────────────
read -rp "Deploy to the above? [y/N] " confirm
if [[ "$confirm" != [yY] ]]; then
  echo "Aborted."
  exit 0
fi

# ── Create Resource Group ──────────────────────────────────────────
echo ""
echo "── Creating resource group: ${RESOURCE_GROUP}..."
az group create \
  --name "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --tags project=sld-bom-extraction environment="$ENV" \
  --output none

# ── Deploy Bicep ───────────────────────────────────────────────────
echo "── Deploying infrastructure..."
DEPLOYMENT_NAME="sldbom-infra-$(date +%Y%m%d%H%M%S)"

az deployment group create \
  --resource-group "$RESOURCE_GROUP" \
  --name "$DEPLOYMENT_NAME" \
  --template-file "${SCRIPT_DIR}/main.bicep" \
  --parameters "$PARAM_FILE" \
  --output none

# ── Collect outputs ────────────────────────────────────────────────
echo ""
echo "── Collecting deployment outputs..."

OUTPUTS=$(az deployment group show \
  --resource-group "$RESOURCE_GROUP" \
  --name "$DEPLOYMENT_NAME" \
  --query properties.outputs \
  --output json)

COSMOS_ENDPOINT=$(echo "$OUTPUTS" | python3 -c "import sys,json; print(json.load(sys.stdin)['cosmosDbEndpoint']['value'])")
COSMOS_ACCOUNT=$(echo "$OUTPUTS" | python3 -c "import sys,json; print(json.load(sys.stdin)['cosmosDbAccountName']['value'])")
STORAGE_ACCOUNT=$(echo "$OUTPUTS" | python3 -c "import sys,json; print(json.load(sys.stdin)['storageAccountName']['value'])")
STORAGE_BLOB_EP=$(echo "$OUTPUTS" | python3 -c "import sys,json; print(json.load(sys.stdin)['storageBlobEndpoint']['value'])")
SB_NAMESPACE=$(echo "$OUTPUTS" | python3 -c "import sys,json; print(json.load(sys.stdin)['serviceBusNamespace']['value'])")
SB_ENDPOINT=$(echo "$OUTPUTS" | python3 -c "import sys,json; print(json.load(sys.stdin)['serviceBusEndpoint']['value'])")

# ── Generate .env.cloud (cloud storage mode) ─────────────────────
CLOUD_ENV_FILE="${SCRIPT_DIR}/../.env.cloud"
LEGACY_ENV_FILE="${SCRIPT_DIR}/../.env.${ENV}.azure"

# Read existing .env for OpenAI / DI settings (preserve user config)
EXISTING_ENV="${SCRIPT_DIR}/../.env"
_read_existing() {
  local key="$1" default="$2"
  if [[ -f "$EXISTING_ENV" ]]; then
    val=$(grep "^${key}=" "$EXISTING_ENV" 2>/dev/null | tail -1 | cut -d'=' -f2- | tr -d '"')
    echo "${val:-$default}"
  else
    echo "$default"
  fi
}

OPENAI_EP=$(_read_existing AZURE_OPENAI_ENDPOINT "<YOUR_OPENAI_ENDPOINT>")
OPENAI_KEY=$(_read_existing AZURE_OPENAI_API_KEY "<YOUR_OPENAI_API_KEY>")
OPENAI_VER=$(_read_existing AZURE_OPENAI_API_VERSION "2025-03-01-preview")
OPENAI_DEP=$(_read_existing AZURE_OPENAI_DEPLOYMENT "gpt-5.4")
DI_EP=$(_read_existing AZURE_DI_ENDPOINT "<YOUR_DI_ENDPOINT>")
DI_KEY=$(_read_existing AZURE_DI_KEY "<YOUR_DI_KEY>")
DI_MODEL=$(_read_existing AZURE_DI_MODEL_ID "prebuilt-layout")

cat > "$CLOUD_ENV_FILE" <<EOF
# ──────────────────────────────────────────────────────────────────
# .env.cloud — Cloud Storage Mode (auto-generated by deploy.sh)
# ──────────────────────────────────────────────────────────────────
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Environment: ${ENV}
# 사용법: cp .env.cloud .env

# ── Storage Mode ──────────────────────────────────────────────────
ENABLE_PERSISTENT_STATE=true

# ── Azure OpenAI ─────────────────────────────────────────────────
AZURE_OPENAI_ENDPOINT=${OPENAI_EP}
AZURE_OPENAI_API_KEY=${OPENAI_KEY}
AZURE_OPENAI_API_VERSION=${OPENAI_VER}
AZURE_OPENAI_DEPLOYMENT=${OPENAI_DEP}

# ── Azure Document Intelligence ─────────────────────────────────
AZURE_DI_ENDPOINT=${DI_EP}
AZURE_DI_KEY=${DI_KEY}
AZURE_DI_MODEL_ID=${DI_MODEL}

# ── Pipeline ─────────────────────────────────────────────────────
HITL_CONFIDENCE_THRESHOLD=0.7
GRID_SIZE=120
VERIFY_MAX_TRIES=10
CHECKPOINT_DIR=./checkpoints
OUTPUT_DIR=./outputs

# ── Azure Cosmos DB (상태 저장) ──────────────────────────────────
AZURE_COSMOS_ENDPOINT=${COSMOS_ENDPOINT}
AZURE_COSMOS_DATABASE=sld-bom
# AZURE_COSMOS_KEY=          # 비워두면 DefaultAzureCredential 사용

# ── Azure Blob Storage (아티팩트 저장) ───────────────────────────
AZURE_STORAGE_ACCOUNT=${STORAGE_ACCOUNT}
AZURE_STORAGE_BLOB_ENDPOINT=${STORAGE_BLOB_EP}
AZURE_STORAGE_ARTIFACTS_CONTAINER=pipeline-artifacts
AZURE_STORAGE_CACHE_CONTAINER=file-cache

# ── Azure Service Bus (이벤트) ───────────────────────────────────
AZURE_SERVICEBUS_NAMESPACE=${SB_ENDPOINT}
AZURE_SERVICEBUS_TASKS_QUEUE=pipeline-tasks
AZURE_SERVICEBUS_EVENTS_TOPIC=pipeline-events
EOF

# Also write legacy .env.{env}.azure for backward compat
cp "$CLOUD_ENV_FILE" "$LEGACY_ENV_FILE"

echo ""
echo "── Deployment complete!"
echo ""
echo "   Cosmos DB:     ${COSMOS_ENDPOINT}"
echo "   Storage:       ${STORAGE_BLOB_EP}"
echo "   Service Bus:   ${SB_ENDPOINT}"
echo ""
echo "   Generated files:"
echo "     .env.cloud          ← Cloud mode (complete, ready to use)"
echo "     .env.${ENV}.azure   ← Legacy format (backward compat)"
echo ""
echo "── 사용법 (How to activate):"
echo ""
echo "   # Cloud 모드 활성화:"
echo "   cp .env.cloud .env"
echo ""
echo "   # Local 모드로 돌아가기:"
echo "   cp .env.local .env    # (or .env.local.example)"
echo ""
echo "   # 또는 Makefile 사용:"
echo "   make mode-cloud       # Cloud 모드"
echo "   make mode-local       # Local 모드"
echo ""
echo "── Prerequisites:"
echo "   pip install azure-cosmos azure-storage-blob azure-identity"
